name: maptiler1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
 
  cupertino_icons: ^1.0.6
  firebase_database: ^11.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
